---
title: "Comparing copy-number profiles using other data"
author:
  - Barbara Hernando, bhernando@cnio.es
  - Blas Chaves, bchavesu@ext.cnio.es
  - Geoff Macintyre, gmacintyre@cnio.es
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    number_sections: no
    theme: simplex
    toc: yes
    toc_float: yes
    df_print: paged
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(collapse = TRUE,comment = "#>")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

## PACKAGES
library(dplyr)
library(CNpare)

# DATA DIRECTORY
path_to_data<-"C:/Users/bhernando/Desktop/CNIO/Projects/BlasProject/quality_tool/data/"
```

## Input data
```{r input}
cells_segcn <- readRDS(paste0(path_to_data, "cellLine_segment_ascat_sc_fixed_purity_tCN.rds"))
mapping <- read.table(paste0(path_to_data,"cellLine_CEL_file_mapping.tsv"),sep="\t",header = T)
```

```{r data_process}
cells_segcn<-getCINProfiles(segcn=cells_segcn, samples=unique(cells_segcn$sample))

#cell lines with CN profile generated with CCLE and GDSC data
ccle <- mapping[mapping$study=="CCLE",c(1,4)]
ccle <- ccle[ccle$fileid %in% cells_segcn$sample,] #with ASCAT CN profile
gdsc <- mapping[mapping$study=="GDSC",c(1,4)] #in GDSC cellid and fileid is the same
gdsc <- gdsc[gdsc$fileid %in% cells_segcn$sample,] #with ASCAT CN profile
both <- ccle[ccle$cellid %in% gdsc$fileid,] 
```


## Chromosome arm copy number
```{r arm_lengths}
#Canonical lengths of chromosomal arms
armlens=data.table::fread(paste0("C:/Users/bhernando/Desktop/pancan_sigs/HSNC&CESC","/hg19.cytoBand.txt.gz"), 
              col.names = c("chromosome","start","end","name","gieStain"))
armlens=armlens[ , .(start=min(start), end = max(end), length = sum(end - start)), 
                 by = .(chromosome, arm = substring(name, 1, 1)) ]
armlens$chromosome = substr(armlens$chromosome, 4, stop = 6)
armlens$chromosome = factor(armlens$chromosome, levels=c(1:22,"X", "Y"))
armlens=armlens[order(armlens$chromosome),]
armlens$chromosome = as.character(armlens$chromosome)
armlens=armlens[armlens$chromosome!="Y",]
```


```{r arm_cn}
# Add chromosome arm in cn segments
chroms <- as.character(unique(cells_segcn$chromosome))
cn <- c()
for (chr in chroms){
    arm <- armlens[armlens$chromosome==chr,]
    c   <- cells_segcn[cells_segcn$chromosome==chr,]
    c$arm[c$end<arm$end[1]] <- arm$arm[1]
    c$arm[c$end>=arm$end[1]] <- arm$arm[2]
    
    cn <- rbind(cn, c)
}
cn <- cn[order(cn$sample,cn$chromosome,cn$arm),]

#ccle
samples=unique(both$fileid)
ccle <- matrix(nrow = nrow(armlens), ncol = length(samples)) #Create the matrix
colnames(ccle) <- samples
rownames(ccle) <- paste0(armlens$chromosome, armlens$arm)

for (a in 1:nrow(armlens)){
    chrom <- armlens[a,chromosome]
    arm   <- armlens[a,arm]
    
    dat <- cn[(cn$chromosome %in% chrom & cn$arm %in% arm), ]
    for (s in 1:length(samples)){
        d <- dat[dat$sample==samples[s], "segVal"]
        ccle[a,s]<- mean(d)
    }
}

#gdsc
samples=unique(both$cellid)
gdsc <- matrix(nrow = nrow(armlens), ncol = length(samples)) #Create the matrix
colnames(gdsc) <- samples
rownames(gdsc) <- paste0(armlens$chromosome, armlens$arm)

for (a in 1:nrow(armlens)){
    chrom <- armlens[a,chromosome]
    arm   <- armlens[a,arm]
    
    dat <- cn[(cn$chromosome %in% chrom & cn$arm %in% arm), ]
    for (s in 1:length(samples)){
        d <- dat[dat$sample==samples[s], "segVal"]
        gdsc[a,s]<- mean(d)
    }
}

#pearson correlations
measures<-getSimilarities(dat1=ccle, dat2=gdsc, method="pearson")
colnames(measures)<-c("fileid", "id","r")
measures<-left_join(measures,both,by="fileid")
list.tophits<-getTopHit(samples=both$cellid, measure=measures[,c(4,2:3)], method="pearson")

#match
list.tophits$equal<-list.tophits[,1]==list.tophits[,2]
top1<-list.tophits[list.tophits$equal,] 
print("Number of samples matching based on arm-level copy number") 
print(paste0(nrow(top1),"/304 samples"))
```

## Ploidy status
```{r ploidy}
#ccle
samples=unique(both$fileid)
ccle <- c() #Create the matrix

for (s in 1:length(samples)){
    c <- c()
    d <- cells_segcn[cells_segcn$sample==samples[s], ]
    d$length<-d$end-d$start
    ploidy <- stats::weighted.mean(d$segVal, d$length)
    c<-cbind(fileid=samples[s], ploidy=ploidy)
    ccle<-rbind(ccle,c)
}

#gdsc
samples=unique(both$cellid)
gdsc <- c() #Create the matrix

for (s in 1:length(samples)){
    c <- c()
    d <- cells_segcn[cells_segcn$sample==samples[s], ]
    d$length<-d$end-d$start
    ploidy <- stats::weighted.mean(d$segVal, d$length)
    c<-cbind(cellid=samples[s], ploidy=ploidy)
    gdsc<-rbind(gdsc,c)
}

ccle<-as.data.frame(ccle)
ccle$ploidy<-round(as.numeric(ccle$ploidy))
gdsc<-as.data.frame(gdsc)
gdsc$ploidy<-round(as.numeric(gdsc$ploidy))

ccle<-left_join(ccle,both,by="fileid")
cells<-left_join(ccle,gdsc,by="cellid")
cells$equal<-cells[,2]==cells[,4]

#match
match<-cells[cells$equal,] 
print("Number of samples matching based on ploidy status") 
print(paste0(nrow(match),"/304 samples"))
```

## Gene level copy number
```{r}
#gene positions
genes = read.table(paste0(path_to_data,"refGenes_positions.txt"),sep="\t")[,c(1:4)]
genes = genes[genes$V4!="",]
genes = genes[!duplicated(genes$V4),] #only one per protein name
genes = genes[!duplicated(genes$V3),] #no duplicates in start position

pos.genes<-genes[,c(4,2,3,3)] #column 3 txStart
colnames(pos.genes)<- c("name", "chromosome", "start", "end")
pos.genes$chromosome = substr(pos.genes$chromosome, 4, stop = 5)
chr<-c(1:22, "X")
pos.genes<-data.table::as.data.table(pos.genes[pos.genes$chromosome %in% chr,])

#ccle
samples=unique(both$fileid)
names=pos.genes$name
ccle <- c()
for (s in 1:length(samples)){
    dat<-data.table::as.data.table(cells_segcn[cells_segcn$sample==samples[s],])
    dat<-dat[,c(5,4,1:3)]
    data.table::setkey(pos.genes, chromosome, start, end)
    overlap <- data.table::foverlaps(dat,pos.genes)
    overlap <-overlap[!is.na(overlap$name),]
    
    ccle<-rbind(ccle,overlap[,c(2,5,6)])
}

#gdsc
samples=unique(both$cellid)
names=pos.genes$name
gdsc <- c()
for (s in 1:length(samples)){
    dat<-data.table::as.data.table(cells_segcn[cells_segcn$sample==samples[s],])
    dat<-dat[,c(5,4,1:3)]
    data.table::setkey(pos.genes, chromosome, start, end)
    overlap <- data.table::foverlaps(dat,pos.genes)
    overlap <-overlap[!is.na(overlap$name),]
    
    gdsc<-rbind(gdsc,overlap[,c(2,5,6)])
}

mccle<-reshape2::acast(ccle, name~sample, value.var="segVal")
mgdsc<-reshape2::acast(gdsc, name~sample, value.var="segVal")

#pearson correlations
measures<-getSimilarities(dat1=mccle, dat2=mgdsc, method="pearson")
colnames(measures)<-c("fileid", "id","r")
measures<-left_join(measures,both,by="fileid")
list.tophits<-getTopHit(samples=both$cellid, measure=measures[,c(4,2:3)], method="pearson")

#match
list.tophits$equal<-list.tophits[,1]==list.tophits[,2]
top1<-list.tophits[list.tophits$equal,] 
print("Number of samples matching by gene-level copy numbers") 
print(paste0(nrow(top1),"/304 samples"))
```
